# Generated by Django 5.1.4 on 2024-12-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_alter_session_user_alter_project_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='highlighted_differences_url',
        ),
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='comparison',
            name='highlighted_differences_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_data',
            field=models.BinaryField(null=True),
        ),
    ]
